add hidaya
mediaelch/mediaelch-meta pull request #2
Opened 2020-10-24 15:03 UTC by Stunkymonkey

2020-10-24 15:12 UTC, bugwelle requested changes
I'll look at your code in a minute. :-)

Could you please adapt the description? Besides that: 👍

2020-10-24 15:12 UTC, bugwelle commented on export_themes.xml
> +    <description>beautiful theme</description>
Could you add a more descriptive text here? e.g. `dark theme with search functionality`?

2020-10-24 15:12 UTC, bugwelle commented on export_themes.xml
> +    <description lang="de">Schönes Theme</description>
Eine etwas bessere Beschreibung wäre noch schöner. :-)

Grüße von 'nem Heidelberger nach Stuttgart. 😃

2020-10-24 15:18 UTC, Stunkymonkey commented on export_themes.xml
> +    <description lang="de">Schönes Theme</description>
sorry war einfach copy&paste aus der `metadata.xml`. Sollte ich auch da noch anpassen :see_no_evil:

2020-10-24 15:20 UTC, bugwelle commented on export_themes.xml
> +    <description lang="de">Schönes Theme</description>
Alles gut, dafür sind Reviews ja da. 😄

2020-10-24 15:20 UTC, Stunkymonkey commented on export_themes.xml
> +    <description lang="de">Schönes Theme</description>
Grüße zurück :smile:

2020-10-24 15:26 UTC, bugwelle commented
Please see https://github.com/Stunkymonkey/hidaya/pull/2

Looks good 👍

2020-10-24 15:48 UTC, Stunkymonkey commented
maybe it makes sense to update to a new /updated release

2020-10-24 15:50 UTC, bugwelle commented
> maybe it makes sense to update to a new /updated release

What do you mean? You can make a new release (and increase `<version>`). Or delete the old tag and create the new one (and update the checksum of this PR). :-)

2020-10-24 17:02 UTC, bugwelle approved these changes

2020-10-24 17:03 UTC, merged

2020-10-24 17:06 UTC, bugwelle commented
<img width="565" alt="Screen Shot 2020-10-24 at 19 04 41" src="https://user-images.githubusercontent.com/1667306/97087657-e9644700-162b-11eb-9e85-cf7d2d0a3dab.png">


Works like a charm! Thank you very much for this theme. I've exported my media files and it works well!

For future changes, please do not update the git tag / GitHub release but instead create a new version and adapt it here. :-)

2020-10-25 00:22 UTC, Stunkymonkey commented
Sure otherwise the shasum will break. It was only done while the PR was not merged yet.

2020-10-26 08:47 UTC, bugwelle commented
> Sure otherwise the shasum will break. It was only done while the PR was not merged yet.

👍